# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from event_booking import event_booking_pb2 as event__booking_dot_event__booking__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in event_booking/event_booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventBookingStub(object):
    """The service definition for booking events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEvent = channel.unary_unary(
                '/eventbooking.EventBooking/CreateEvent',
                request_serializer=event__booking_dot_event__booking__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=event__booking_dot_event__booking__pb2.Event.FromString,
                _registered_method=True)
        self.BookEvent = channel.unary_unary(
                '/eventbooking.EventBooking/BookEvent',
                request_serializer=event__booking_dot_event__booking__pb2.BookEventRequest.SerializeToString,
                response_deserializer=event__booking_dot_event__booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/eventbooking.EventBooking/CancelBooking',
                request_serializer=event__booking_dot_event__booking__pb2.CancelBookingRequest.SerializeToString,
                response_deserializer=event__booking_dot_event__booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/eventbooking.EventBooking/ListEvents',
                request_serializer=event__booking_dot_event__booking__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=event__booking_dot_event__booking__pb2.ListEventsResponse.FromString,
                _registered_method=True)


class EventBookingServicer(object):
    """The service definition for booking events.
    """

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=event__booking_dot_event__booking__pb2.CreateEventRequest.FromString,
                    response_serializer=event__booking_dot_event__booking__pb2.Event.SerializeToString,
            ),
            'BookEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.BookEvent,
                    request_deserializer=event__booking_dot_event__booking__pb2.BookEventRequest.FromString,
                    response_serializer=event__booking_dot_event__booking__pb2.BookingResponse.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=event__booking_dot_event__booking__pb2.CancelBookingRequest.FromString,
                    response_serializer=event__booking_dot_event__booking__pb2.BookingResponse.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=event__booking_dot_event__booking__pb2.ListEventsRequest.FromString,
                    response_serializer=event__booking_dot_event__booking__pb2.ListEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventbooking.EventBooking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eventbooking.EventBooking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventBooking(object):
    """The service definition for booking events.
    """

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventbooking.EventBooking/CreateEvent',
            event__booking_dot_event__booking__pb2.CreateEventRequest.SerializeToString,
            event__booking_dot_event__booking__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventbooking.EventBooking/BookEvent',
            event__booking_dot_event__booking__pb2.BookEventRequest.SerializeToString,
            event__booking_dot_event__booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventbooking.EventBooking/CancelBooking',
            event__booking_dot_event__booking__pb2.CancelBookingRequest.SerializeToString,
            event__booking_dot_event__booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventbooking.EventBooking/ListEvents',
            event__booking_dot_event__booking__pb2.ListEventsRequest.SerializeToString,
            event__booking_dot_event__booking__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
