# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_booking/event_booking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event_booking/event_booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!event_booking/event_booking.proto\x12\x0c\x65ventbooking\"P\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rtotal_tickets\x18\x03 \x01(\x05\x12\x16\n\x0e\x62ooked_tickets\x18\x04 \x01(\x05\"9\n\x12\x43reateEventRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rtotal_tickets\x18\x02 \x01(\x05\"9\n\x10\x42ookEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0bnum_tickets\x18\x02 \x01(\x05\"=\n\x14\x43\x61ncelBookingRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0bnum_tickets\x18\x02 \x01(\x05\"3\n\x0f\x42ookingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x13\n\x11ListEventsRequest\"9\n\x12ListEventsResponse\x12#\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x13.eventbooking.Event2\xcd\x02\n\x0c\x45ventBooking\x12\x46\n\x0b\x43reateEvent\x12 .eventbooking.CreateEventRequest\x1a\x13.eventbooking.Event\"\x00\x12L\n\tBookEvent\x12\x1e.eventbooking.BookEventRequest\x1a\x1d.eventbooking.BookingResponse\"\x00\x12T\n\rCancelBooking\x12\".eventbooking.CancelBookingRequest\x1a\x1d.eventbooking.BookingResponse\"\x00\x12Q\n\nListEvents\x12\x1f.eventbooking.ListEventsRequest\x1a .eventbooking.ListEventsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_booking.event_booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=51
  _globals['_EVENT']._serialized_end=131
  _globals['_CREATEEVENTREQUEST']._serialized_start=133
  _globals['_CREATEEVENTREQUEST']._serialized_end=190
  _globals['_BOOKEVENTREQUEST']._serialized_start=192
  _globals['_BOOKEVENTREQUEST']._serialized_end=249
  _globals['_CANCELBOOKINGREQUEST']._serialized_start=251
  _globals['_CANCELBOOKINGREQUEST']._serialized_end=312
  _globals['_BOOKINGRESPONSE']._serialized_start=314
  _globals['_BOOKINGRESPONSE']._serialized_end=365
  _globals['_LISTEVENTSREQUEST']._serialized_start=367
  _globals['_LISTEVENTSREQUEST']._serialized_end=386
  _globals['_LISTEVENTSRESPONSE']._serialized_start=388
  _globals['_LISTEVENTSRESPONSE']._serialized_end=445
  _globals['_EVENTBOOKING']._serialized_start=448
  _globals['_EVENTBOOKING']._serialized_end=781
# @@protoc_insertion_point(module_scope)
